### ISSUE TITLE
请问这个PHP脚本可以自动启动或者自动重连吗

### ISSUE THREAD

**Issue by WangNingkai** [dantmnf/drcom-client#1]
PHP脚本放到openwrt里断线了可以重连吗，在windows上出现下面的问题
[![error](https://snag.gy/qVaEot.jpg "error")](https://snag.gy/qVaEot.jpg "error")

**Comment by dantmnf** [comment]
脚本里有自动重连逻辑，但可能没有覆盖到所有情况

至于第二个问题，把配置文件里的网卡名字改一下
